"""add sensor type and measurment_time fields

Revision ID: 6fd922e637c1
Revises: 275aa4c49340
Create Date: 2024-02-21 22:44:51.924572

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6fd922e637c1"
down_revision: Union[str, None] = "275aa4c49340"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("devices", sa.Column("sensor_type", sa.String(), nullable=True))
    op.add_column("measurements", sa.Column("time_", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("measurements", "time_")
    op.drop_column("devices", "sensor_type")
    # ### end Alembic commands ###
